StreamPlay/StreamPlay/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from StreamPlay import views
from raccomander_systems.reviews_filter.videogame_by_reviews import fit_algo, create_model

urlpatterns = [
                  path('user_management/', include('user_management.urls')),
                  path('games_management/', include('games_management.urls')),
                  path('orders/', include('orders.urls')),
                  path('admin/', admin.site.urls),
                  path('stats/', views.stats, name='stats_page'),
                  path('', views.home,name='home'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#create_model()
fit_algo()

StreamPlay/orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add/<str:name>/', views.add_cart, name='add-cart'),
    path('empty/', views.empty_cart, name='empty-cart'),
    path('remove/<str:name>',views.remove_cart,name='remove-cart'),
    path('', views.cart, name='cart'),
    path('checkout', views.checkout, name='checkout')
]

StreamPlay/user_management/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from user_management import views

urlpatterns = [
    path('registration', views.registration, name='registration'),
    path('logout', views.logoutview, name='logout'),
    path('login', views.loginview, name='login'),
    path('profile/<slug>', views.Profile.as_view(), name='user-details'),
    path('profile/update/', views.UpdateProfile, name='update'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
         views.activate, name='activate'),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='user_management/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='user_management/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='user_management/password_reset_complete.html'),
         name='password_reset_complete'),

]

StreamPlay/user_management/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField


class MyAccountManager(BaseUserManager):

    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("User must have an email address")
        if not username:
            raise ValueError("User must have an username")

        user = self.model(
            email=self.normalize_email(email),
            username=username
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):

        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
        )

        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    birthday = models.DateField(null=True)
    phone_number = PhoneNumberField(blank=True)
    nationality = CountryField()
    picture = models.ImageField(upload_to='profile_image', blank=True)
    bio = models.TextField(blank=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    objects = MyAccountManager()

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

    def get_absolute_url(self):
        return reverse('user-details', args=[self.username])

    @classmethod
    def create(cls, email, username):
        return User(email=email, username=username, name="Dummy", surname="User")


class PrivacyField(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    show_name = models.BooleanField(default=True)
    show_surname = models.BooleanField(default=True)
    show_email = models.BooleanField(default=True)
    show_birthday = models.BooleanField(default=True)
    show_library = models.BooleanField(default=True)

    @classmethod
    def create(cls, userid):
        privacy_field = cls(user=userid)
        return privacy_field

StreamPlay/user_management/forms.py
import datetime

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm

from user_management.models import User, PrivacyField


class RegistrationForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = (
            "name", "surname", "birthday", "email", "phone_number", "nationality", "username", "password1", "password2")
        widgets = {'name': forms.TextInput(attrs={'class': 'form-control'}),
                   'surname': forms.TextInput(attrs={'class': 'form-control'}),
                   'birthday': forms.TextInput(attrs={'class': 'form-control'}),
                   'email': forms.TextInput(attrs={'class': 'form-control'}),
                   'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
                   'nationality': forms.Select(attrs={'class': 'form-control'}),
                   'username': forms.TextInput(attrs={'class': 'form-control'}),
                   }

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'registration-crispy-form'
        self.helper.add_input(Submit('submit', 'Submit'))

    def clean(self):
        if self.is_valid():
            if self.cleaned_data['username'].__contains__("/"):
                raise forms.ValidationError("Usernames with '/' character are not allowed")
            if self.cleaned_data['birthday']>datetime.date.today():
                raise forms.ValidationError("Welcome John Titor")
            if User.objects.filter(email=self.cleaned_data['email']).exists():
                raise forms.ValidationError("Email already exists")
            if User.objects.filter(username=self.cleaned_data['username']).exists():
                raise forms.ValidationError("Username already exists")



class UserAuthenticationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'type': 'password', 'placeholder': 'Password', 'id': 'inputPassword'}))

    class Meta:
        model = User
        fields = ('email', 'password')
        widgets = {'email': forms.TextInput(
            attrs={'class': 'form-control', 'type': 'email', 'placeholder': 'Email Address', 'id': 'inputEmail'}),
        }

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Invalid login: check your email or password")


class PrivacyForm(forms.ModelForm):
    class Meta:
        model = PrivacyField
        fields = ['show_email','show_library','show_birthday','show_name','show_surname']


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name','surname','nationality','picture','birthday','bio']

StreamPlay/user_management/views.py
from compat import render_to_string
from django.contrib.auth import login, authenticate
from django.contrib.auth import logout
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.db.models import Q
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import DetailView
from django.views.generic.list import MultipleObjectMixin

from StreamPlay.token import account_activation_token
from orders.models import Library
from orders.views import ShoppingCart
from user_management.forms import RegistrationForm, UserAuthenticationForm, UserForm, PrivacyForm
from user_management.models import User, PrivacyField


def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your StreamPlay account.'
            message = render_to_string('user_management/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return render(request, 'user_management/new_registration_mail_sent.html')
    else:
        form = RegistrationForm()
    return render(request, 'user_management/registration.html', {'registration_form': form})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(id=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        shopping_cart = ShoppingCart.create(userid=user)
        shopping_cart.save()

        library = Library.create(userid=user)
        library.save()

        privacy = PrivacyField.create(userid=user)
        privacy.save()

        login(request, user)

        return redirect('user-details', user.username)
    else:
        return HttpResponse('Activation link is invalid!')


def loginview(request):
    context = {}

    user = request.user
    if user.is_authenticated:
        return redirect("profile/" + user.username)

    if request.POST:
        form = UserAuthenticationForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)

            if user:
                login(request, user)
                return redirect("profile/" + user.username)

    else:
        form = UserAuthenticationForm()

    context['login_form'] = form
    return render(request, 'user_management/login.html', context)


def logoutview(request):
    logout(request)
    return redirect('login')


class Profile(DetailView, MultipleObjectMixin):
    model = User
    fields = ['name', 'surname', 'username', 'picture']
    template_name = 'user_management/profile.html'
    slug_field = 'username'

    def get_context_data(self, **kwargs):
        library = Library.objects.get(UserId=self.object.id).getVideogames().order_by('name')
        context = super(Profile, self).get_context_data(object_list=library, **kwargs)
        privacy = PrivacyField.objects.get(user=self.object.id)
        context['privacy'] = privacy
        return context


def UpdateProfile(request):
    privacy_fields = PrivacyField.objects.get(user_id=request.user.id)
    if request.POST:
        user_form = UserForm(request.POST, files=request.FILES, instance=request.user)
        privacy_form = PrivacyForm(request.POST, instance=privacy_fields)
        if user_form.is_valid() and privacy_form.is_valid():
            user_form.save()
            privacy_form.save()
            request.user.save()
            privacy_fields.save()
            print(request.POST.get('picture'))
            return HttpResponseRedirect(reverse('user-details', kwargs={'slug': request.user.username}))
        else:
            user_form = UserForm(instance=request.user)
            privacy_form = PrivacyForm(instance=privacy_fields)
    else:
        user_form = UserForm(instance=request.user)
        privacy_form = PrivacyForm(instance=privacy_fields)

    return render(request, "user_management/update_profile.html",
                  {'user_form': user_form, 'privacy_form': privacy_form})


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data) | Q(username=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "user_management/password_reset_email.html"

                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    message = render_to_string(email_template_name, c)
                    print(message)
                    print(user.email)
                    email = EmailMessage(subject, message, to=[user.email])
                    email.send()
                    return redirect("password_reset_done")
    password_reset_form = PasswordResetForm()
    if request.user.is_authenticated:
        subject = "Password Reset Requested"
        email_template_name = "user_management/password_reset_email.html"

        c = {
            "email": request.user.email,
            'domain': '127.0.0.1:8000',
            'site_name': 'Website',
            "uid": urlsafe_base64_encode(force_bytes(request.user.pk)),
            "user": request.user,
            'token': default_token_generator.make_token(request.user),
            'protocol': 'http',
        }
        message = render_to_string(email_template_name, c)
        email = EmailMessage(subject, message, to=[request.user.email])
        email.send()
        return redirect("password_reset_done")

    return render(request=request, template_name="user_management/password_reset_html.html",
                  context={"password_reset_form": password_reset_form})

StreamPlay/user_management/templates/user_management/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

StreamPlay/user_management/templates/user_management/base_table.html
{% extends 'navbar.html' %}
{% load static %}

{% block title %}{% endblock %}


{% block content %}
    {% block table_before %}

    {% endblock %}

    <table class="table table-striped">
        <thead>
            <tr>
                {% block table_head %}

                {% endblock %}
            </tr>
        </thead>
        <tbody>
             {% block table_body %}

             {% endblock %}
        </tbody>
    </table>
    {% block table_after %}

    {% endblock %}
{% endblock %}

StreamPlay/user_management/templates/user_management/login.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="{% static "user_management/css/loginstyle.css" %}">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <form class="form-signin" method="post">{% csrf_token %}
                            <h5 class="card-title text-center">Sign In</h5>
                            <div class="form-label-group">
                                {{ login_form.email }}
                                <label for="inputEmail">Email address</label>
                            </div>

                            <div class="form-label-group">
                                {{ login_form.password }}
                                <label for="inputPassword">Password</label>
                            </div>

                            {% if login_form.errors %}
                                {% for field in login_form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{ error|escape }}</strong>
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in login_form.non_field_errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                    Forgot your password? <a href="{% url "password_reset" %}">Reset your password</a>
                                {% endfor %}
                            {% endif %}
                            <button class="btn btn-lg btn-success btn-block text-uppercase mt-3" type="submit">Sign in</button>
                            New member? <a href="{% url 'registration' %}">Register now!</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </body>
{% endblock %}

StreamPlay/user_management/templates/user_management/new_registration_mail_sent.html
{% extends 'navbar.html' %}


{% block content %}

	<!--Password reset sent-->
	<div class="container p-5">
  	<h2 class="font-weight-bold mt-3">Confirm your e-mail</h2>
		<hr>
        <p>Welcome to Streamplay!</p>
        <p>Check your e-mail to verify your account and start using your brand new profile!</p>
  </div>

{% endblock %}

StreamPlay/user_management/templates/user_management/password_reset_complete.html
{% extends "navbar.html" %}

{% block content %}

  <!--Password Reset Complete-->
    <div class="container p-4">
	    <h2 class="font-weight-bold mt-3">Password reset complete</h2>
		<hr>
        <p>Your password has been set. You may go ahead and log in now.</p>
        <a href="{% url 'login' %}" class="btn btn-primary">Log in</a>
    </div>

{% endblock %}

StreamPlay/user_management/templates/user_management/password_reset_confirm.html
{% extends "navbar.html" %}

{% block content %}

  {% load crispy_forms_tags %}

  <!--Password Reset Confirm-->
    <div class="container p-5">
	    <h2 class="font-weight-bold mt-3">Password Reset Confirm</h2>
		<hr>
        <p>Please enter your new password.</p>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-primary" type="submit">Reset password</button>
        </form>
    </div>

{% endblock %}

StreamPlay/user_management/templates/user_management/password_reset_done.html
{% extends 'navbar.html' %}


{% block content %}

	<!--Password reset sent-->
	<div class="container p-5">
  	<h2 class="font-weight-bold mt-3">Password reset sent</h2>
		<hr>
		<p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.<br>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
  </div>

{% endblock %}

StreamPlay/user_management/templates/user_management/password_reset_email.html
{% autoescape off %}
Hello,

We received a request to reset the password for your account for this email address. To initiate the password reset process for your account, click the link below.

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

This link can only be used once. If you need to reset your password again, please visit {{ protocol }}://{{domain}} and request another reset.

If you did not make this request, you can simply ignore this email.

Sincerely,
The Website Team

{% endautoescape %}

StreamPlay/user_management/templates/user_management/password_reset_html.html
{% extends 'navbar.html' %}


{% block content %}

	{% load crispy_forms_tags %}          

	<!--Reset Password-->
	<div class="container p-5">
  	 	<h2 class="font-weight-bold mt-3">Reset Password</h2>
		<hr>
		<p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
        <form method="POST">
            {% csrf_token %}
            {{ password_reset_form|crispy }}                    
            <button class="btn btn-primary" type="submit">Send email</button>
        </form>
  	</div> 

{% endblock %}

StreamPlay/user_management/templates/user_management/registration.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
    <meta charset="UTF-8">
    <title>Register</title>
    <link rel="stylesheet" type="text/css" href="{% static "user_management/css/loginstyle.css" %}">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <form class="form-signin" method="post" autocomplete="off">{% csrf_token %}
                            <h5 class="card-title text-center">Register</h5>
                            <div class="form-label-group">
                                {{ registration_form.name }}
                                <label>Name</label>
                            </div>

                            <div class="form-label-group">
                                {{ registration_form.surname }}
                                <label>Surname</label>
                            </div>
                            <div  class="form-label-group " >
                                {{ registration_form.birthday }}
                                <label>Birthday (Format: yyyy-mm-dd)</label>

                            </div>
                            <div class="form-label-group">
                                {{ registration_form.email }}
                                <label>Email address</label>
                            </div>
                            <div class="form-label-group">
                                {{ registration_form.phone_number }}
                                <label>Phone Number</label>
                            </div>
                            <div class="form-label-group">
                                Nationality
                                {{ registration_form.nationality }}
                            </div>
                            <div class="form-label-group">
                                {{ registration_form.username }}
                                <label>Username</label>
                            </div>
                            <div class="form-label-group">
                                {{ registration_form.password1 }}
                                <label>Password</label>
                            </div>
                            <div class="form-label-group">
                                {{ registration_form.password2 }}
                                <label>Repeat password</label>
                            </div>
                            {% if registration_form.errors %}
                                {% for field in registration_form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{ error|escape }}</strong>
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in registration_form.non_field_errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <button class="btn btn-lg btn-success btn-block text-uppercase mt-3" type="submit">Register now</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </body>
{% endblock %}
{% block js %}
     <script>
        $( function() {
            $( "#id_birthday" ).datepicker({
                dateFormat: 'yy-mm-dd'
                }
            );
        } );
    </script>

{% endblock %}

StreamPlay/user_management/templates/user_management/update_profile.html
{% extends 'navbar.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% block head %}
    <title>Update profile</title>
{% endblock %}
{% block content %}
    <h1>Update your account information</h1>
    <p>Change your password: <a href="{% url 'password_reset' %}" class="btn btn-warning"><i class="fas fa-key"></i></a></p>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form|crispy}}
        {{ privacy_form|crispy }}
        {{ user_form.errors }}
        {{ privacy_form.errors }}
        <button class="btn btn-primary border-dark" type="submit">Save changes</button>
    </form>
{% endblock %}

{% block js %}
    <script>
        $( function() {
            $( "#id_birthday" ).datepicker({
                    dateFormat: 'yy-mm-dd'
                }
            );
        } );
    </script>
{% endblock %}