StreamPlay/StreamPlay/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from StreamPlay import views
from raccomander_systems.reviews_filter.videogame_by_reviews import fit_algo, create_model

urlpatterns = [
                  path('user_management/', include('user_management.urls')),
                  path('games_management/', include('games_management.urls')),
                  path('orders/', include('orders.urls')),
                  path('admin/', admin.site.urls),
                  path('stats/', views.stats, name='stats_page'),
                  path('', views.home,name='home'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#create_model()
fit_algo()

StreamPlay/games_management/urls.py
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path

from games_management import views

urlpatterns = [

    path('videogame_details/<slug>', views.videogame_details.as_view(), name='videogame-details'),
    path('update_videogame/<slug>', staff_member_required(views.UpdateVideogame.as_view()), name='update-videogame'),
    path('delete_videogame/<slug>', staff_member_required(views.DeleteVideogame.as_view()), name='delete-videogame'),
    path('', views.VideogameList, name='videogame-list'),
    path('upload_review/<str:name>', views.upload_review, name='upload-review'),
    path('update_review/<str:name>', views.update_review, name='update-review'),
    path('jsonVideogames', views.jsonVideogame, name='jsonVideogames'),


]

StreamPlay/orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add/<str:name>/', views.add_cart, name='add-cart'),
    path('empty/', views.empty_cart, name='empty-cart'),
    path('remove/<str:name>',views.remove_cart,name='remove-cart'),
    path('', views.cart, name='cart'),
    path('checkout', views.checkout, name='checkout')
]

StreamPlay/games_management/models.py
import datetime

from background_task import background
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Avg
from django.dispatch import receiver

from user_management.models import User


class Videogame(models.Model):
    name = models.CharField(unique=True, max_length=64)
    price = models.DecimalField(max_digits=6, decimal_places=2, validators=[MinValueValidator(1)])

    GENREOPTIONS = (
        ("Action", "Action"),
        ("Indie", "Indie"),
        ("Strategy", "Strategy"),
        ("RPG", "RPG"),
        ("Animation & Modeling", "Animation & Modeling"),
        ("Casual", "Casual"),
        ("Simulation", "Simulation"),
        ("Racing", "Racing"),
        ("Adventure", "Adventure"),
        ("Violent", "Violent"),
        ("Nudity", "Nudity"),
        ("Free to Play", "Free to Play"),
        ("Sports", "Sports"),
        ("Gore", "Gore"),
        ("Massively Multiplayer", "Massively Multiplayer"),
        ("Utilities", "Utilities"),
        ("Design & Illustration", "Design & Illustration"),
        ("Education", "Education"),
        ("Web Publishing", "Web Publishing"),
        ("Sexual Content", "Sexual Content"),
        ("Audio Production", "Audio Production"),
        ("Photo Editing", "Photo Editing"),
        ("Early Access", "Early Access"),
    )
    genre = models.CharField(max_length=25, choices=GENREOPTIONS)
    sid = models.IntegerField(default=0, null=True, blank=True)
    description = models.TextField(max_length=5000)
    release_date = models.DateField()
    on_sale = models.BooleanField(default=False)
    on_sale_last_date = models.DateField(blank=True, null=True, default=None)
    sale_percentage = models.DecimalField(max_digits=2, decimal_places=0, validators=[MinValueValidator(1)], blank=True,
                                          null=True, default=None)
    picture = models.ImageField(upload_to='')

    image_1 = models.ImageField(upload_to='', default=None, null=True, blank=True)
    image_2 = models.ImageField(upload_to='', default=None, null=True, blank=True)
    image_3 = models.ImageField(upload_to='', default=None, null=True, blank=True)

    avg_review = models.DecimalField(max_digits=1, decimal_places=0,
                                     validators=[MinValueValidator(1), MaxValueValidator(5)], default=1)

    in_creation = models.BooleanField(default=True, editable=False)

    class Meta:
        verbose_name = 'Videogame'
        verbose_name_plural = 'Videogames'

    @classmethod
    def create(cls,name,price,releasedate,genre,sid):
        return cls(name=name,price=price,release_date=releasedate,genre=genre,sid=sid)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"videogame_details/{self.name}"

    def get_discounted_price(self):
        if self.on_sale:
            return (self.price * (100 - int(self.sale_percentage))) / 100

    @background
    def remove_discount(videogameId):
        v = Videogame.objects.get(id=videogameId)
        v.sale_percentage = 0
        v.on_sale = False
        v.on_sale_last_date = None
        v.save()

    def update_rating(self):
        new_avg_rate = Review.objects.filter(Videogame=self.id).aggregate(Avg('rate'))
        self.avg_review = new_avg_rate['rate__avg']
        self.save()

    def save(self, *args, **kwargs):
        # Each time a game is created we need to re-do the model based on their description for advice similar games
        if self.in_creation:
            from raccomander_systems.description_based_approach.videogames_by_orders import create_model
            self.__in_creation = False
            create_model()

        # When the game become in sale we schedule the remove_discount function that will be run in the on_sale_last_date at midnight
        if (self.on_sale):
            date = datetime.datetime(self.on_sale_last_date.year, self.on_sale_last_date.month,
                                     self.on_sale_last_date.day)
            self.remove_discount(self.id, schedule=date)

        old = Videogame.objects.filter(id=getattr(self, "id", None)).first()

        super().save(*args, **kwargs)
        if old:
            if (old.description != self.description or old.name != self.name):
                from raccomander_systems.description_based_approach.videogames_by_orders import create_model
                create_model()





class Review(models.Model):
    UserId = models.ForeignKey(User, on_delete=models.CASCADE)
    Videogame = models.ForeignKey(Videogame, on_delete=models.CASCADE)
    rate = models.DecimalField(max_digits=1, decimal_places=0,
                               validators=[MinValueValidator(1), MaxValueValidator(5)], default=0)
    comment = models.TextField(max_length=1024)

    def __str__(self):
        return self.UserId.email + " - " + self.Videogame.name

    @classmethod
    def create(cls, userid, videogame, rate, comment):
        review = cls(UserId=userid)
        review.Videogame = videogame
        review.rate = rate
        review.comment = comment
        return review

    class Meta:
        unique_together = (('UserId', 'Videogame'),)

StreamPlay/games_management/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django_starfield import *


class SearchForm(forms.Form):
    OPTIONS = (
        ("-", "-"),
        ("Action", "Action"),
        ("Indie", "Indie"),
        ("Strategy", "Strategy"),
        ("RPG", "RPG"),
        ("Animation & Modeling", "Animation & Modeling"),
        ("Casual", "Casual"),
        ("Simulation", "Simulation"),
        ("Racing", "Racing"),
        ("Adventure", "Adventure"),
        ("Violent", "Violent"),
        ("Nudity", "Nudity"),
        ("Free to Play", "Free to Play"),
        ("Sports", "Sports"),
        ("Gore", "Gore"),
        ("Massively Multiplayer", "Massively Multiplayer"),
        ("Utilities", "Utilities"),
        ("Design & Illustration", "Design & Illustration"),
        ("Education", "Education"),
        ("Web Publishing", "Web Publishing"),
        ("Sexual Content", "Sexual Content"),
        ("Audio Production", "Audio Production"),
        ("Photo Editing", "Photo Editing"),
        ("Early Access", "Early Access"),
    )

    REVIEW_OPTION = (
        ("1", "1"),
        ("2", "2"),
        ("3", "3"),
        ("4", "4"),
        ("5", "5"),

    )

    name = forms.CharField(required=False)
    genre = forms.CharField(required=False, widget=forms.Select(choices=OPTIONS))
    price_from = forms.DecimalField(required=False, min_value=0, max_value=1000, max_digits=3)
    price_to = forms.DecimalField(required=False, min_value=0, max_value=1000, max_digits=3)
    on_sale = forms.BooleanField(required=False)
    avg_review = forms.DecimalField(required=False, min_value=0, max_value=5, max_digits=3,
                                    widget=forms.Select(choices=REVIEW_OPTION))

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'search-crispy-form'
        self.helper.add_input(Submit('submit', 'Search'))


class ReviewForm(forms.Form):
    rating = forms.IntegerField(required=True, widget=Stars, initial=1)
    your_review = forms.CharField(required=False, max_length=1024,
                                  widget=forms.Textarea(attrs={'cols': 100, 'rows': 10}))

    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'review-crispy-form'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Submit'))

StreamPlay/games_management/views.py
import json

from django.core import serializers
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import DetailView, UpdateView, DeleteView

from games_management.forms import ReviewForm
from games_management.models import Videogame, Review
from orders.models import ShoppingCart, Library
from raccomander_systems.reviews_filter.videogame_by_reviews import create_model, fit_algo


class videogame_details(DetailView):
    model = Videogame
    fields = ['name', 'price',
              'description', 'release_date',
              'on_sale', 'on_sale_last_date',
              'sale_percentage']
    template_name = 'games_management/videogame_details.html'
    slug_field = 'name'

    def get_context_data(self, **kwargs, ):
        context = super(videogame_details, self).get_context_data(**kwargs)

        # Se il gioco è posseduto dal current user
        if Library.objects.filter(UserId=self.request.user.id, Videogames__name=self.object.name):
            is_owned = True
        else:
            is_owned = False

        # Se il gioco è recensito dal current user
        if Review.objects.filter(UserId=self.request.user.id, Videogame=self.object.id):
            review = Review.objects.get(UserId=self.request.user.id, Videogame=self.object.id)
            reviewed = True
            context['your_review'] = review
        else:
            reviewed = False
            context['your_review'] = None

        # Se il gioco è attualmente nel carrello del current user
        if ShoppingCart.objects.filter(UserId=self.request.user.id, Videogames__name=self.object.name):
            in_cart = True
        else:
            in_cart = False

        # Recensioni degli utenti del gioco ( Tranne la recensione del current user)
        context['reviews'] = Review.objects.filter(Videogame__name=self.object.name).exclude(
            UserId=self.request.user.id)
        context['is_owned'] = is_owned
        context['is_reviewed'] = reviewed
        context['in_cart'] = in_cart
        if reviewed:
            context['review_form'] = ReviewForm(initial={'rating': review.rate, 'your_review': review.comment})
        else:
            context['review_form'] = ReviewForm
        return context


class UpdateVideogame(UpdateView):
    model = Videogame
    template_name = 'games_management/update_videogame.html'
    slug_field = 'name'
    fields = ['name', 'price', 'genre', 'description', 'release_date',
              'on_sale', 'on_sale_last_date', 'sale_percentage', 'picture', 'image_1', 'image_2', 'image_3']

    def get_success_url(self):
        return reverse('videogame-details', kwargs={'slug': self.object.name})


def VideogameList(request):
    context = {}
    if request.method == 'POST':
        context['initial_name'] = request.POST.get('name')
    else:
        context['initial_name'] = ""
    template_name = 'games_management/videogame_list2.html'
    return render(request, template_name, context)


def upload_review(request, name):
    if request.method == "GET":
        return redirect('videogame-list')
    videogame_to_review = Videogame.objects.get(name=name)
    review = Review.create(userid=request.user,
                           videogame=videogame_to_review,
                           rate=request.POST["rating"],
                           comment=request.POST["your_review"])
    review.save()
    videogame_to_review.update_rating()

    # update review model e calcolo della similarità
    create_model()
    fit_algo()

    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


def update_review(request, name):
    if request.method == "GET":
        return redirect('videogame-list')
    videogame_to_review = Videogame.objects.get(name=name)

    review = Review.objects.get(UserId=request.user.id, Videogame__name=name)
    review.rate = request.POST["rating"]
    review.comment = request.POST["your_review"]

    review.save()
    videogame_to_review.update_rating()
    # update review model e calcolo della similarità
    create_model()
    fit_algo()
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


def jsonVideogame(request):
    object_list = Videogame.objects.all()
    serialized_objects = serializers.serialize('json', object_list)
    json_objects = json.loads(serialized_objects)
    list_objects = []
    for index in range(len(json_objects)):
        list_objects.append(json_objects[index]['fields'])

    for item in list_objects:
        item.pop("description")
        item.pop("on_sale_last_date")
    return HttpResponse(json.dumps(list_objects), content_type='application/json;charset=utf-8')


class DeleteVideogame(DeleteView):
    model = Videogame
    slug_field = 'name'

    def get_success_url(self):
        from raccomander_systems.description_based_approach.videogames_by_orders import create_model
        create_model()
        return reverse('videogame-list')

StreamPlay/games_management/templates/games_management/update_videogame.html
{% extends 'navbar.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block head %}
    <style>
        #id_description {
            width: 50%;
        }
    </style>

    <style>
        .image {
            height: 10%;
            width: 10%;
        }

    </style>

{% endblock %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}
        {% for field in form %}
            {{ field|as_crispy_field }}
            {% if field.name == 'picture' and form.instance.picture.url %}
                <img class="image" src="{{ form.instance.picture.url }}"
                     id="videogame_picture">
            {% endif %}
            {% if field.name == 'image_1' and form.instance.image_1.url %}
                <img class="image" src="{{ form.instance.image_1.url }}"
                     id="image_1">
            {% endif %}
            {% if field.name == 'image_2' and form.instance.image_2.url %}
                <img class="image" src="{{ form.instance.image_2.url }}"
                     id="image_2">
            {% endif %}
            {% if field.name == 'image_3' and form.instance.image_3.url %}
                <img class="image" src="{{ form.instance.image_3.url }}"
                     id="image_3">
            {% endif %}


        {% endfor %}
        <br>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>


{% endblock %}

{% block js %}
    <script>

        $(function () {
            c
            $("#id_release_date").datepicker({
                    dateFormat: 'yy-mm-dd'
                }
            );
        });
    </script>
{% endblock %}

StreamPlay/games_management/templates/games_management/videogame_confirm_delete.html
{% extends 'navbar.html' %}

{% block head %}
    <title>
    Delete {{ object }}
    </title>
    <style>

        #outer-div{
            border-style: solid;
            border-color: #ff1c23;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="mt-5 pb-5 pt-5" id="outer-div">
        <div class="d-flex justify-content-center">
            <h2>Are you sure you want to delete "{{ object }}"?</h2>
        </div>
        <form class="d-flex justify-content-center" method="post">{% csrf_token %}
            <input class="btn btn-danger" type="submit" value="Confirm">
        </form>

    </div>
{% endblock%}

StreamPlay/games_management/templates/games_management/videogame_details.html
{% extends 'navbar.html' %}
{% load tags %}
{% load crispy_forms_tags %}
{% load thumbnail %}
{% load static %}
{% block head %}
    <style>
        .checked {
            color: orange;
        }
    </style>
    <title>{{ object.name }} details</title>
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-between">
        <h1>{{ object.name }}</h1>
        {% if object.avg_review < 3 %}
            <h1 style="color: red">{{ object.avg_review }} <i class="fas fa-star"></i></h1>
        {% elif object.avg_review > 3 %}
            <h1 style="color: green">{{ object.avg_review }} <i class="fas fa-star"></i></h1>
        {% else %}
            <h1 style="color: darkgoldenrod">{{ object.avg_review }} <i class="fas fa-star"></i></h1>
        {% endif %}
    </div>
    <div class="d-flex justify-content-between">
        <div id="carousel" class="carousel slide" data-ride="carousel" style="width: 60%">

            <div class="carousel-inner">
                <div class="carousel-item active">
                    {% if object.picture %}
                        <img src="{{ object.picture|thumbnail_url:'videogame_details'}}" class="d-block w-100">
                    {% else %}
                        <img class="d-block w-100" src="https://steamcdn-a.akamaihd.net/steam/apps/{{object.sid}}/header.jpg" alt="First slide">
                    {% endif %}

                </div>
                {% if object.image_1 %}
                    <div class="carousel-item ">
                        <img class="d-block w-100" src="{{ object.image_1|thumbnail_url:'videogame_details' }}">
                    </div>
                {% endif %}
                {% if object.image_2 %}
                    <div class="carousel-item ">
                        <img class="d-block w-100" src="{{ object.image_2|thumbnail_url:'videogame_details' }}">
                    </div>
                {% endif %}
                {% if object.image_3 %}
                    <div class="carousel-item ">
                        <img class="d-block w-100" src="{{ object.image_3|thumbnail_url:'videogame_details' }}">
                    </div>
                {% endif %}

            </div>
            <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <div style="width: 30%">
            <h1>Details</h1>
            <h5>
                <p>Genre: {{ object.genre }}</p>
                <p>Release date: {{ object.release_date }}</p>
                {% if object.on_sale %}
                    <p style="color: green">Price:
                        <del>{{ object.price }} €</del>
                        {{ object.get_discounted_price }} € -{{ object.sale_percentage }}%
                    </p>
                    <p style="color: green">On sale until {{ object.on_sale_last_date }}</p>
                {% else %}
                    <p>Price: {{ object.price }} €</p>
                {% endif %}
                {% if request.user.is_authenticated %}
                    {% if is_owned %}
                        <p><a class="btn btn-success disabled" data-toggle="tooltip" title="Game already owned"><i
                                class="fas fa-check-square"></i></a> You own this game!</p>
                    {% elif in_cart %}
                        <p><a href="{% url 'cart' %}" class="btn btn-outline-warning" data-toggle="tooltip"
                              title="Game in cart"><i class="fas fa-shopping-cart"></i></a></p>
                    {% else %}
                        <p><a href="{% url 'add-cart' videogame.name %}" class="btn btn-outline-success"
                              data-toggle="tooltip" title="Add to cart"><i class="fas fa-shopping-cart"></i></a></p>

                    {% endif %}
                    {% if request.user.is_admin %}
                        <p><a href="{% url 'update-videogame' videogame.name %}" class="btn btn-outline-warning"
                              data-toggle="tooltip" title="Update videogame info"><i class="fas fa-edit"></i></a>
                        <a href="{% url 'delete-videogame' videogame.name %}" class="btn btn-outline-danger"
                              data-toggle="tooltip" title="Delete videogame"><i class="fas fa-trash-alt"></i></a>
                        </p>
                    {% endif %}
                {% else %}
                    <p><a href="{% url 'login' %}" class="btn btn-outline-success" data-toggle="tooltip"
                          title="Log in to buy this game!"><i class="fas fa-sign-in-alt"></i></a></p>
                {% endif %}
            </h5>
        </div>
    </div>
    <h4 class="d-flex justify-content-between mt-3">About the game:</h4>
    <div>
        {{ object.description|safe }}
    </div>
    <div class="mt-3">
        <h1 class="d-flex justify-content-between">Reviews
            {% if request.user.is_authenticated and is_owned %}
                {% if is_reviewed %}
                    <button onclick="reviewGame()" class="btn btn-outline-primary">Update your review</button>
                {% else %}
                    <button onclick="reviewGame()" class="btn btn-outline-primary">Review the game!</button>
                {% endif %}
            {% endif %}
        </h1>
        {% if request.user.is_authenticated and is_owned %}
            {% if is_reviewed %}
                <div class="card">
                    <h5 class="card-header d-flex justify-content-between">
                        <div>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star {% if your_review.rate >= 2 %}checked{% endif %}"></span>
                            <span class="fa fa-star {% if your_review.rate >= 3 %}checked{% endif %}"></span>
                            <span class="fa fa-star {% if your_review.rate >= 4 %}checked{% endif %}"></span>
                            <span class="fa fa-star {% if your_review.rate >= 5 %}checked{% endif %}"></span>
                        </div>
                        <a href="{{ your_review.UserId.get_absolute_url }}">
                            Author : {{ your_review.UserId.username }}
                        </a>
                    </h5>
                    <div class="card-body">
                        <p class="card-text">{{ your_review.comment }}</p>
                    </div>
                </div>
            {% endif %}
        {% endif %}
        <div id="review-field" style="display: none">
            {% if is_reviewed %}
                <form action="{% url 'update-review' object.name %}" method="POST" id="reviewForm">
            {% else %}
                <form action="{% url 'upload-review' object.name %}" method="POST" id="reviewForm">
            {% endif %}
            {% csrf_token %}
            {% crispy review_form review_form.helper %}
            </form>
        </div>
        {% if reviews %}
            {% for review in reviews %}
                <div class="card">
                    <h5 class="card-header d-flex justify-content-between">
                        <div>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star {% if review.rate >= 2 %}checked{% endif %}"></span>
                            <span class="fa fa-star {% if review.rate >= 3 %}checked{% endif %}"></span>
                            <span class="fa fa-star {% if review.rate >= 4 %}checked{% endif %}"></span>
                            <span class="fa fa-star {% if review.rate >= 5 %}checked{% endif %}"></span>
                        </div>
                        <a href="{{ review.UserId.get_absolute_url }}">
                            Author : {{ review.UserId.username }}
                        </a>
                    </h5>
                    <div class="card-body">
                        <p class="card-text">{{ review.comment }}</p>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            {% if not your_review %}
                <div class="d-flex justify-content-center">
                    <img src="{% static "games_management/images/review.png" %}">
                </div>
                <div class="d-flex justify-content-center">
                    <h5>And here's where i keep my reviews... if i had one!</h5>
                </div>
            {% endif %}
        {% endif %}
    </div>
    </div>

{% endblock %}
{% block js %}
    <script>
        function reviewGame() {
            revForm = document.getElementById('review-field')
            if (revForm.style.display === "none") {
                revForm.style.display = "block";
            } else {
                revForm.style.display = "none";
            }
        }
    </script>
{% endblock %}

StreamPlay/games_management/templates/games_management/videogame_list.html
<!-- Old version of videogame_list -->

{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load thumbnail %}
{% load tags %}

{% block head %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="{% static "games_management/css/loader.css" %}"/>

    <title>Search videogames</title>


{% endblock %}

{% block content %}

    <div class="loader-wrapper">
        <span class="loader"><span class="loader-inner"></span></span>
    </div>
    <form action="{% url 'videogame-list' %}" method="get"
          class="form-inline d-flex justify-content-around mb-3">
        {% crispy SearchForm SearchForm.helper %}
    </form>

    {% if object_list %}
        <table class="table table-striped  mt-3" id="Results">
            <thead class="text-center">
            <th></th>
            <th>
                Title
            </th>
            <th>
                Genre
            </th>
            <th>
                Price
            </th>
            <th>
                Rating
            </th>
            </thead>
            <tbody>
            {% for instance in object_list %}
                <tr>
                    <td class="align-middle text-center" style="width: 12%">
                        {% if instance.picture %}
                            <a href='{{ instance.get_absolute_url }}'>
                                <img src="{{ instance.picture.url }}" width="231" height="87"></a>
                        {% else %}
                            <a href='{{ instance.get_absolute_url }}'><img
                                    src="https://steamcdn-a.akamaihd.net/steam/apps/{{ instance.sid }}/header.jpg"
                                    width="231" height="87"></a>
                        {% endif %}
                    </td>
                    <td class="align-middle text-center" style="width: 22%">
                        <a href='{{ instance.get_absolute_url }}'
                           style="text-decoration: darkblue"> {{ instance.name }} </a>
                    </td>
                    <td class="align-middle text-center" style="width: 22%">
                        {{ instance.genre }}
                    </td>
                    <td class="align-middle text-center" style="width: 22%">
                        {{ instance.price }} €
                    </td>
                    <td class="align-middle text-center " style="width: 22%">
                        {% if instance.avg_review < 3 %}
                            <div style="color: red">{{ instance.avg_review }} <i class="fas fa-star"></i></div>
                        {% elif instance.avg_review > 3 %}
                            <div style="color: green">{{ instance.avg_review }} <i class="fas fa-star"></i></div>
                        {% else %}
                            <div style="color: darkgoldenrod">{{ instance.avg_review }} <i class="fas fa-star"></i>
                            </div>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>

    {% else %}
        <div class="d-flex justify-content-center mt-3">
            <img src="{% static 'games_management/images/empty_list.jpg' %}">
        </div>
        <h4 class="d-flex justify-content-center">Nothing found... search something else!</h4>
    {% endif %}

{% endblock %}


{% block js %}

    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>

    <script>
        $(window).on("load", function () {
            $(".loader-wrapper").fadeOut("slow");
        })
    </script>

    <script>
        $(document).ready(function () {
            $('#Results').DataTable({
                "bScrollInfinite": true,
                "bScrollCollapse": true,
                "sScrollY": "200px",
            });
        });
    </script>



{% endblock %}